### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by Caponia** [cyberdisarray/HideonCombat#1]
NO.1
Message: Interface\AddOns\HideonCombat\HideonCombat.lua:13: attempt to call global 'ColorClass' (a nil value)
Time: 02/10/18 22:47:32
Count: 2
Stack: Interface\AddOns\HideonCombat\HideonCombat.lua:13: attempt to call global 'ColorClass' (a nil value)
[C]: in function `ColorClass'
Interface\AddOns\HideonCombat\HideonCombat.lua:13: in function `CallGlobal'
Interface\AddOns\HideonCombat\HideonCombat.lua:75: in function <Interface\AddOns\HideonCombat\HideonCombat.lua:74>

Locals: 

NO.2
Message: Interface\AddOns\HideonCombat\HideonCombat.lua:13: attempt to call global 'ColorClass' (a nil value)
Time: 02/10/18 22:47:32
Count: 2
Stack: Interface\AddOns\HideonCombat\HideonCombat.lua:13: attempt to call global 'ColorClass' (a nil value)
[C]: in function `ColorClass'
Interface\AddOns\HideonCombat\HideonCombat.lua:13: in function `CallGlobal'
Interface\AddOns\HideonCombat\HideonCombat.lua:93: in function <Interface\AddOns\HideonCombat\HideonCombat.lua:92>

Locals:

**Comment by cyberdisarray** [comment]
@Caponia Thank you for your report. yeah forgot about that its from my other addon, Let me know if the problem return. Update on the way,
