### ISSUE TITLE
One issue

### ISSUE THREAD

**Issue by Caponia** [cyberdisarray/HideonCombat#2]
In combat,this addon will hide the minimap.
Is this good?
![wowscrnshot_021318_211616](https://user-images.githubusercontent.com/33995465/36151707-5380d2ec-1103-11e8-9cd5-e282a088e9dd.jpg)

**Comment by cyberdisarray** [comment]
It's normal, this just happen in a open world scenario. I did this because in a open world you normally don't use your mini-map for anything while in combat. On raids, dgs, bgs the minimapa still there. =P
Please reply this message so I can mark it's solved if everything is fine for you.

**Comment by rikeni** [comment]
My mini-map disappears in dungeons and raids.  I am not sure what info to provide to help debug.

**Comment by Caponia** [comment]
In fact ,minimap is hide in the cambat

![wowscrnshot_021418_162420](https://user-images.githubusercontent.com/33995465/36194150-9ec3a9c8-11a3-11e8-905f-82abd582467c.jpg)

**Comment by cyberdisarray** [comment]
I will update the addon today (7.3.0.3) . So let me know if the minimap stop to hide on dgs and raids.

**Comment by Caponia** [comment]
I will test that fix.
Thank you.

**Comment by Caponia** [comment]
That's OK!
![wowscrnshot_021418_225204](https://user-images.githubusercontent.com/33995465/36219797-831cbe76-11f3-11e8-9bcc-84a12452910e.jpg)
